# Generated by Django 4.0.3 on 2022-04-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shangpin',
            name='sp_lasttime',
        ),
        migrations.AddField(
            model_name='shangpin',
            name='sp_pic',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image'),
        ),
    ]
