# Generated by Django 4.0.3 on 2022-04-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_shangpin_sp_lasttime_shangpin_sp_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shangpin',
            name='sp_pinglun',
        ),
        migrations.AlterField(
            model_name='shangpin',
            name='sp_master',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='auctions.pinglun'),
        ),
    ]
