# Generated by Django 4.0.3 on 2022-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_pinglun_sp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangpin',
            name='sp_start',
            field=models.BooleanField(default=True),
        ),
    ]
