# Generated by Django 4.0.3 on 2022-04-23 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_shangpin_sp_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangpin',
            name='sp_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='shoucang',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.shangpin', to_field='sp_name')),
                ('spuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
